name: drought
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.3.1
  - r-tidyverse=2.0.0
  - r-showtext=0.9
  - r-maps=3.4
  - wget>=1.20.3
  - snakemake=7.32.3
  - graphviz=8.1.0
  - coreutils=9.4
